version: "3"
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    volumes:
      - ./app
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    enviroment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db
  db:
    image: postgres:13-alphine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    enviroment:
      - POSTFRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data: